/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlueprintEditorRouteImport } from './routes/blueprint-editor'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ListsListRouteImport } from './routes/lists.$list'
import { Route as RecordsTypeRouteImport } from './routes/records.$type'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintEditorRoute = BlueprintEditorRouteImport.update({
  id: '/blueprint-editor',
  path: '/blueprint-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsListRoute = ListsListRouteImport.update({
  id: '/lists/$list',
  path: '/lists/$list',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsTypeRoute = RecordsTypeRouteImport.update({
  id: '/records/$type',
  path: '/records/$type',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blueprint-editor': typeof BlueprintEditorRoute
  '/dashboard': typeof DashboardRoute
  '/lists/$list': typeof ListsListRoute
  '/records/$type': typeof RecordsTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blueprint-editor': typeof BlueprintEditorRoute
  '/dashboard': typeof DashboardRoute
  '/lists/$list': typeof ListsListRoute
  '/records/$type': typeof RecordsTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blueprint-editor': typeof BlueprintEditorRoute
  '/dashboard': typeof DashboardRoute
  '/lists/$list': typeof ListsListRoute
  '/records/$type': typeof RecordsTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/blueprint-editor' | '/dashboard' | '/lists/$list' | '/records/$type'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/blueprint-editor' | '/dashboard' | '/lists/$list' | '/records/$type'
  id:
    | '__root__'
    | '/'
    | '/blueprint-editor'
    | '/dashboard'
    | '/lists/$list'
    | '/records/$type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlueprintEditorRoute: typeof BlueprintEditorRoute
  DashboardRoute: typeof DashboardRoute
  ListsListRoute: typeof ListsListRoute
  RecordsTypeRoute: typeof RecordsTypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprint-editor': {
      id: '/blueprint-editor'
      path: '/blueprint-editor'
      fullPath: '/blueprint-editor'
      preLoaderRoute: typeof BlueprintEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/$list': {
      id: '/lists/$list'
      path: '/lists/$list'
      fullPath: '/lists/$list'
      preLoaderRoute: typeof ListsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/$type': {
      id: '/records/$type'
      path: '/records/$type'
      fullPath: '/records/$type'
      preLoaderRoute: typeof RecordsTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlueprintEditorRoute: BlueprintEditorRoute,
  DashboardRoute: DashboardRoute,
  ListsListRoute: ListsListRoute,
  RecordsTypeRoute: RecordsTypeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
